### PR TITLE
Added Navagation

### PR DESCRIPTION
**Pull request by Blummer92**

### CODE REVIEW

**Comment by taion** [comment]
@bpas247 is there a way we can prevent codesandbox from opening PRs against this repo?

**Comment by bpas247** [comment]
> @bpas247 is there a way we can prevent codesandbox from opening PRs against this repo?

Hmm, I'm not sure if I understand you correctly. I don't think CodeSandbox opens any PRs by itself? Or do you mean is there a way we can restrict CodeSandbox from creating a sandbox for open PRs?

**Comment by taion** [comment]
this PR looks like it was somehow auto generated? like from the branch name and all

**Comment by bpas247** [comment]
yeah it does seem auto generated, hmm.

@Blummer92 How did you go about creating this PR?

**Comment by Blummer92** [comment]
I'm not sure what you guys are referring to?

**Comment by bpas247** [comment]
> I'm not sure what you guys are referring to?

You know what it probably doesn't matter, let's just move past it for now. I'm not really sure why this PR is deleting all of the old examples though... Or what this PR is supposed to be accomplishing

**Comment by bpas247** [comment]
I'm going to go ahead and close this for now :) as it's not very clear what this PR is doing.

**Pull request closed without merging**
